services:
  - type: web
    name: ouresults-scrapper
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flaskapp:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
